version: '3'


services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate;
                      python manage.py collectstatic --noinput;
                      python manage.py createsuperuser --noinput;
                      gunicorn OsuFormHub.wsgi --bind 0.0.0.0:80 --reload --workers 1"
    ports:
      - "80:80"
    volumes:
      - "./src:/src"
    environment:
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=12345678
